name: rovo_app
description: Rovo application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  http:
  json_annotation:
  get_it:
  cached_network_image:
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter packages pub run build_runner build
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/chat.json
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-Bold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
          weight: 500